services:
  build:
    build:
      args:
        - TCISD_VERSION=local
    pull_policy: if_not_present
    image: idelchi/tcisd:dev
    container_name: tcisd
    hostname: tcisd
    user: user
    volumes:
      - .:/home/user/ws
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
    networks:
      - tcisd

  kit:
    pull_policy: if_not_present
    image: idelchi/devenv:latest
    container_name: kit
    hostname: kit
    volumes:
      - $PWD:/home/ci/ws
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /home/ci/ws

# The default network used to connect the containers
# Is not needed when the services are defined inside one project,
# but can be used to connect external containers to the network
networks:
  tcisd:
    name: tcisd
    driver: bridge
