// Command tcisd provides a tool for stripping comments from code files.
//
// Usage:
//
//	# Lint files for comments
//	tcisd lint [flags] [path ...]
//
//	# Remove comments from files
//	tcisd format [flags] [path ...]
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/tcisd/internal/parse"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

func main() {
	if err := parse.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}
}
