// Command tcisd provides a tool for stripping comments from code files.
//
// Usage:
//
//	# Lint files for comments
//	tcisd lint [flags] [path ...]
//
//	# Remove comments from files
//	tcisd format [flags] [path ...]
package main

import (
	"os"

	"github.com/idelchi/tcisd/internal/logic"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

func main() {
	exitCode := logic.Run(version)
	os.Exit(exitCode)
}
