package main

import (
	"fmt"
	"os"

	"github.com/idelchi/tcisd/internal/parse"
)

var version = "unknown - unofficial & generated by unknown"

func main() {
	if err := parse.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}
}
