name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    uses: idelchi/devenv/.github/workflows/gorelease.yml@dev
    permissions:
      contents: write
    with:
      config: .devenv/settings/.goreleaser.yaml
